### PR TITLE
add ability to launch string kernels

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Allows to do this:
```Julia
           copy_source = """
                __kernel void copy(
                    __global float *dest,
                    __global float *source
                ){
                int gid = get_global_id(0);
                dest[gid] = source[gid];
                }
            """
            source = rand(CLArray{Float32}, 1023, 11)
            dest = zeros(CLArray{Float32}, size(source))
            gpu_call(:copy => copy_source, dest, (dest, source))
            Array(dest) == Array(source)
```
Note, that the caching of the functor is not very nice, so for repeated calls, one might want to do
this part manually:
https://github.com/JuliaGPU/CLArrays.jl/blob/37ed840d5c4aabb4cbc9f5dd6d3e8d131d766d4d/src/compilation.jl#L12

**Comment by SimonDanisch** [comment]
@ranocha

**Comment by SimonDanisch** [comment]
@maleadt any idea whats up with this:
```
INFO: Testing CLArrays
ERROR: LoadError: CLError(code=-1001, CL_PLATFORM_NOT_FOUND_KHR)
Stacktrace:
 [1] macro expansion at /var/lib/buildbot/workers/julia/CLArrays-julia06-x86-64bit/depot/v0.6/OpenCL/src/macros.jl:6 [inlined]
 [2] platforms() at /var/lib/buildbot/workers/julia/CLArrays-julia06-x86-64bit/depot/v0.6/OpenCL/src/platform.jl:21
 [3] devices() at /var/lib/buildbot/workers/julia/CLArrays-julia06-x86-64bit/depot/v0.6/OpenCL/src/platform.jl:104
 [4] devices() at /var/lib/buildbot/workers/julia/CLArrays-julia06-x86-64bit/depot/v0.6/CLArrays/src/device.jl:6
 [5] anonymous at ./<missing>:?
 [6] include_from_node1(::String) at ./loading.jl:576
 [7] include(::String) at ./sysimg.jl:14
 [8] process_options(::Base.JLOptions) at ./client.jl:305
 [9] _start() at ./client.jl:371
while loading /var/lib/buildbot/workers/julia/CLArrays-julia06-x86-64bit/depot/v0.6/CLArrays/test/runtests.jl, in expression starting on line 4
```

**Comment by maleadt** [comment]
@SimonDanisch fixed

**Comment by SimonDanisch** [comment]
Thank you :)

**Pull request merged**
