### PR TITLE
Added support for Adapt.jl

### PR DESCRIPTION
**Pull request by Maaarcocr**
In line to what is was already done for CuArrays, I've added support for Adapt in CLArrays and also created a `cl` function that works similarly to the `cu` function in CuArrays. 

Please let me know if you want me to add tests.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Thank you!

>Please let me know if you want me to add tests.

Would be nice, if you have the time :)

**Comment by Maaarcocr** [comment]
@SimonDanisch I will add them soon! In the meanwhile I pushed one more commit that deletes a line of code. This change makes `cl([Dual(1,2)])` work. The line that was deleted was there because I mainly copied it from CuArrays. I'm no entirely sure what the implications are, so I would love if you could quickly review it 😄

**Comment by Maaarcocr** [comment]
@SimonDanisch just pushed some basics tests 😄 I was thinking that it would also be beneficial to test `cl()` with things like `ForwardDiff.Dual` and `TrackedArrays` from Flux, but I'm not sure if it makes sense to add these dependencies to the test-suite.

**Comment by SimonDanisch** [comment]
Hm, maybe we should do that - I really don't want to break Flux compatibility. We can add Flux as test REQUIRE! :)

**Comment by MikeInnes** [comment]
@Maaarcocr Best to leave that line in there. The reason for it is so that when you do `cl([1.0,2.0,3.0])` it'll produce an array of Float32, not Float64, which will be very slow or even break on most GPUs. I don't really think we need to support dual numbers moving to the GPU, but if we ever do it's easy to add a line to fix that.

Would also be great to export `cl` so it's easily available; it seems common enough to merit that. In CuArrays I also made it work as an array constructor syntax, i.e. `cu[1, 2, 3]`; although `@cu[1,2,3]` might be more general.

**Comment by MikeInnes** [comment]
This now works though 🎉 

```julia
julia> using Flux, CLArrays.Shorthands

julia> m = Chain(Dense(10, 5, relu), Dense(5, 2), softmax)
Chain(Dense(10, 5, NNlib.relu), Dense(5, 2), NNlib.softmax)

julia> m = cl(m)
Chain(Dense(10, 5, NNlib.relu), Dense(5, 2), NNlib.softmax)

julia> m[1].W
Tracked 5×10 CLArrays.CLArray{Float64,2}:
 -0.106548   -0.169599     0.533831   …  -0.0394621  -0.257771   -0.46787  
 -0.624177   -0.00718461   0.258335       0.275833    0.0330991   0.560168 
 -0.0776361  -0.230228    -0.0545424      0.448682    0.452049   -0.57525  
  0.210329   -0.317022     0.368344       0.0119867   0.190483    0.327332 
  0.189214    0.243617     0.0214457     -0.284973    0.0895423  -0.0968204
```

**Pull request merged**
